Implement code-value pair extraction and mapping
HicServices/RdmpDicom pull request #393
Opened 2024-01-18 15:46 UTC by jas88

Implement ICD11 code and meaning capture, mapping

2024-02-21 18:07 UTC, rkm requested changes
Looks fine, but could you add a couple of basic tests?

2024-05-20 22:57 UTC, jas88 commented
Also includes fix to Github actions for #416

2024-05-31 14:59 UTC, jas88 commented
@rkm Not an exciting test but now has a simple SR with two levels of info on a Dermatofibrosis diagnosis, and checks that makes it into the resulting DataTable

2024-05-31 23:31 UTC, rkm approved these changes

2024-06-01 03:30 UTC, merged